package de.infolektuell.gradle.jextract.extensions;

import org.gradle.api.Action;
import org.gradle.api.Named;
import org.gradle.api.file.Directory;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Nested;
import org.jetbrains.annotations.NotNull;

/** A configuration for a library to be generated by Jextract */
public abstract class LibraryHandler implements Named {
    /** The header file to generate bindings for */
    @NotNull
    public abstract RegularFileProperty getHeader();

    /** Additional directories to be appended to include search paths */
    @NotNull
    public abstract ListProperty<@NotNull Directory> getIncludes();

    /** Macros to be defined, in the format `name=value` */
    @NotNull
    public abstract ListProperty<@NotNull String> getDefinedMacros();

    /** The package name for the generated code */
    @NotNull
    public abstract Property<@NotNull String> getTargetPackage();

    /** The name for the class generated from the header file, derived from the header file if missing */
    @NotNull
    public abstract Property<@NotNull String> getHeaderClassName();

    /** List of definitions to be included */
    @Nested
    @NotNull
    public abstract WhitelistHandler getWhitelist();

    /** Configures the list of definitions to be included */
    public final void whitelist(@NotNull Action<@NotNull WhitelistHandler> action) {
        action.execute(this.getWhitelist());
    }

    /** Native libraries to be loaded by generated code (either names or paths starting with colon) */
    @NotNull
    public abstract ListProperty<@NotNull String> getLibraries();

    /** Load libraries in the library symbol lookup, using either `System.load` or `System.loadLibrary`, useful for libraries in java.library.path */
    @NotNull
    public abstract Property<@NotNull Boolean> getUseSystemLoadLibrary();

    /** specify the directory to place generated files. */
    @NotNull
    public abstract DirectoryProperty getOutput();

    /** Generate source files instead of class files (Jextract 21 and below) */
    @NotNull
    public abstract Property<@NotNull Boolean> getGenerateSourceFiles();
}
