package de.infolektuell.gradle.jextract.extensions;

import org.gradle.api.Action;
import org.gradle.api.Named;
import org.gradle.api.file.Directory;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.SetProperty;
import org.gradle.api.tasks.Nested;
import org.jspecify.annotations.NonNull;

/**
 * A configuration for a library to be generated by Jextract
 */
public abstract class LibraryHandler implements Named {
    /**
     * The header files to generate bindings for
     */
    public abstract ListProperty<@NonNull String> getHeaders();

    /**
     * Directories to be appended to include search paths, searched from left to right.
     * @return A list property to add the header directories.
     */
    public abstract ListProperty<@NonNull Directory> getIncludePath();

    /**
     * Directories containing native binaries to be appended to the library search path.
     * @return A list property to add the binaries directories.
     */
    public abstract ListProperty<@NonNull Directory> getLibraryPath();

    /**
     * Native libraries to be loaded by generated code (either names or paths starting with colon)
     */
    public abstract ListProperty<@NonNull String> getLibraries();

    /**
     * Directories containing legal notice documents for this library.
     * @return A set property to add the directories.
     */
    public abstract SetProperty<@NonNull Directory> getLegalNotices();

    /**
     * Macros to be defined, in the format `name=value`
     */
    public abstract ListProperty<@NonNull String> getDefinedMacros();

    /**
     * The name for the class generated from the header file, derived from the header file if missing
     */
    public abstract Property<@NonNull String> getHeaderClassName();

    /**
     * List of definitions to be included
     */
    @Nested
    public abstract WhitelistHandler getWhitelist();

    /**
     * Configures the list of definitions to be included
     */
    public final void whitelist(Action<@NonNull WhitelistHandler> action) {
        action.execute(this.getWhitelist());
    }

    /**
     * The package name for the generated code
     */
    public abstract Property<@NonNull String> getTargetPackage();

    /**
     * Load libraries in the library symbol lookup, using either `System.load` or `System.loadLibrary`, useful for libraries in java.library.path
     */
    public abstract Property<@NonNull Boolean> getUseSystemLoadLibrary();

    /**
     * specify the directory to place generated files.
     */
    public abstract DirectoryProperty getOutput();

    /**
     * Generate source files instead of class files (Jextract 21 and below)
     */
    public abstract Property<@NonNull Boolean> getGenerateSourceFiles();
}
