package de.infolektuell.gradle.jextract.extensions;

import org.gradle.api.Action;
import org.gradle.api.NamedDomainObjectSet;
import org.gradle.api.model.ObjectFactory;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * Configures a source Set to include libraries generated by Jextract
 */
public abstract class SourceSetExtension {
    @NotNull
    private final NamedDomainObjectSet<@NotNull LibraryHandler> libraries;
    /**
     * The name of this extension how it is accessible from build.gradle or build.gradle.kts
     */
    @NotNull
    public static final String EXTENSION_NAME = "jextract";

    @Inject
    public SourceSetExtension(@NotNull ObjectFactory objects) {
        super();
        this.libraries = objects.namedDomainObjectSet(LibraryHandler.class);
    }

    /**
     * Libraries that were defined in the jextract extension. Their generated source and class outputs will be added to the source set.
     */
    @NotNull
    public final NamedDomainObjectSet<@NotNull LibraryHandler> getLibraries() {
        return this.libraries;
    }

    /**
     * Configures the libraries that were defined in the jextract extension. Their generated source and class outputs will be added to the source set.
     */
    public final void libraries(@NotNull Action<@NotNull NamedDomainObjectSet<@NotNull LibraryHandler>> action) {
        action.execute(this.libraries);
    }
}
