package de.infolektuell.gradle.jextract.extensions;

import org.gradle.api.Action;
import org.gradle.api.NamedDomainObjectSet;
import org.gradle.api.model.ObjectFactory;
import org.jspecify.annotations.NonNull;

import javax.inject.Inject;

/**
 * Configures a source Set to include libraries generated by Jextract
 */
public abstract class SourceSetExtension {
    private final NamedDomainObjectSet<@NonNull LibraryHandler> libraries;
    /**
     * The name of this extension how it is accessible from build.gradle or build.gradle.kts
     */
    public static final String EXTENSION_NAME = "jextract";

    @Inject
    public SourceSetExtension(@NonNull ObjectFactory objects) {
        super();
        this.libraries = objects.namedDomainObjectSet(LibraryHandler.class);
    }

    /**
     * Libraries that were defined in the jextract extension. Their generated source and class outputs will be added to the source set.
     */
    public final NamedDomainObjectSet<@NonNull LibraryHandler> getLibraries() {
        return this.libraries;
    }

    /**
     * Configures the libraries that were defined in the jextract extension. Their generated source and class outputs will be added to the source set.
     */
    public final void libraries(Action<@NonNull NamedDomainObjectSet<@NonNull LibraryHandler>> action) {
        action.execute(this.libraries);
    }
}
