package de.infolektuell.gradle.jextract.extensions;

import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.SetProperty;
import org.jspecify.annotations.NonNull;

/**
 * A configuration for included definitions in a library to be generated by Jextract
 */
public abstract class WhitelistHandler {
    /**
     * Functions to include
     */
    public abstract SetProperty<@NonNull String> getFunctions();

    /**
     * Macro or constant enums to include
     */
    public abstract SetProperty<@NonNull String> getConstants();

    /**
     * Struct definitions to include
     */
    public abstract SetProperty<@NonNull String> getStructs();

    /**
     * Type definitions to include
     */
    public abstract SetProperty<@NonNull String> getTypedefs();

    /**
     * Union definitions to include
     */
    public abstract SetProperty<@NonNull String> getUnions();

    /**
     * Global variables to include
     */
    public abstract SetProperty<@NonNull String> getVariables();

    /**
     * A file containing all includes as args, maybe generated by --dump-includes
     */
    public abstract RegularFileProperty getArgFile();
}
