package de.infolektuell.gradle.jextract.extensions;

import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.SetProperty;
import org.jetbrains.annotations.NotNull;

/** A configuration for included definitions in a library to be generated by Jextract */
public abstract class WhitelistHandler {
    /** Functions to include */
    @NotNull
    public abstract SetProperty<@NotNull String> getFunctions();

    /** Macro or constant enums to include */
    @NotNull
    public abstract SetProperty<@NotNull String> getConstants();

    /** Struct definitions to include */
    @NotNull
    public abstract SetProperty<@NotNull String> getStructs();

    /** Type definitions to include */
    @NotNull
    public abstract SetProperty<@NotNull String> getTypedefs();

    /** Union definitions to include */
    @NotNull
    public abstract SetProperty<@NotNull String> getUnions();

    /** Global variables to include */
    @NotNull
    public abstract SetProperty<@NotNull String> getVariables();

    /** A file containing all includes as args, maybe generated by --dump-includes */
    @NotNull
    public abstract RegularFileProperty getArgFile();
}
