package de.infolektuell.gradle.jextract.extensions;

import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.SetProperty;
import org.jspecify.annotations.NonNull;

/// A configuration for included definitions in a library to be generated by Jextract
public abstract class WhitelistHandler {
    /// Creates a new instance.
    public WhitelistHandler() { super(); }

    /// Functions to include
    /// @return A set property to configure the functions
    public abstract SetProperty<@NonNull String> getFunctions();

    /// Macro or constant enums to include
    /// @return A set property to configure the constants
    public abstract SetProperty<@NonNull String> getConstants();

    /// Struct definitions to include
    /// @return A set property to configure the structs
    public abstract SetProperty<@NonNull String> getStructs();

    /// Type definitions to include
    /// @return A set property to configure the type definitions
    public abstract SetProperty<@NonNull String> getTypedefs();

    /// Union definitions to include
    /// @return A set property to configure the union definitions
    public abstract SetProperty<@NonNull String> getUnions();

    /// Global variables to include
    /// @return A set property to configure the variables
    public abstract SetProperty<@NonNull String> getVariables();

    /// A file containing all includes as args, maybe generated by --dump-includes
    /// @return A property to configure the arg file
    public abstract RegularFileProperty getArgFile();
}
