package de.infolektuell.gradle.jextract.extensions

import org.gradle.api.Action
import org.gradle.api.NamedDomainObjectSet
import org.gradle.api.model.ObjectFactory
import javax.inject.Inject

/** Configures a source Set to include libraries generated by Jextract */
abstract class SourceSetExtension @Inject constructor(objects: ObjectFactory) {
    /** Libraries that were defined in the jextract extension. Their generated source and class outputs will be added to the source set. */
    val libraries: NamedDomainObjectSet<LibraryHandler> = objects.namedDomainObjectSet(LibraryHandler::class.java)
    fun libraries(action: Action<in NamedDomainObjectSet<LibraryHandler>>) {
        action.execute(libraries)
    }
    companion object {
        const val EXTENSION_NAME = "jextract"
    }
}
