package de.infolektuell.gradle.jextract.extensions

import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.SetProperty

/** A configuration for included definitions in a library to be generated by Jextract */
abstract class WhitelistHandler {
    /** Functions to include */
    abstract val functions: SetProperty<String>
    /** Macro or constant enums to include */
    abstract val constants: SetProperty<String>
    /** Struct definitions to include */
    abstract val structs: SetProperty<String>
    /** Type definitions to include */
    abstract val typedefs: SetProperty<String>
    /** Union definitions to include */
    abstract val unions: SetProperty<String>
    /** Global variables to include */
    abstract val variables: SetProperty<String>
    /** A file containing all includes as args, maybe generated by --dump-includes */
    abstract val argFile: RegularFileProperty
}
