package de.infolektuell.gradle.jextract.extensions

import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Provider
import org.gradle.api.provider.ProviderFactory
import javax.inject.Inject

/** A configuration for included definitions in a library to be generated by Jextract */
abstract class WhitelistHandler @Inject constructor(providers: ProviderFactory) {
    /** Functions to include */
    abstract val functions: ListProperty<String>
    /** Macro or constant enums to include */
    abstract val constants: ListProperty<String>
    /** Struct definitions to include */
    abstract val structs: ListProperty<String>
    /** Type definitions to include */
    abstract val typedefs: ListProperty<String>
    /** Union definitions to include */
    abstract val unions: ListProperty<String>
    /** Global variables to include */
    abstract val variables: ListProperty<String>
    /** A file containing all includes as args, maybe generated by --dump-includes */
    abstract val argFile: RegularFileProperty
    /** All included definitions in a map provider, simplifies usage by task */
    val mapProvider: Provider<Map<String, List<String>>> = providers.provider {
        mapOf(
            "function" to functions.get(),
            "constant" to constants.get(),
            "struct" to structs.get(),
            "typedef" to typedefs.get(),
            "union" to unions.get(),
            "var" to variables.get(),
        )
    }
}
