name: Publish package

on:
  release:
    types: [created]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-gh-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish Plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}"
        run: ./gradlew publish
